let SPMSubject = [
    { name: "Bahasa Melayu", gred: "Gred" },
    { name: "Bahasa Inggeris", gred: "Gred" },
    { name: "Bahasa Cina", gred: "Gred" },
    { name: "Bahasa Tamil", gred: "Gred" },
    { name: "Bahasa Arab Komunikasi", gred: "Gred" },
    { name: "Bahasa Punjabi", gred: "Gred" },
    { name: "Bahasa Perancis", gred: "Gred" },
    { name: "Bahasa Iban", gred: "Gred" },
    { name: "Pengetahuan Sains Sukan", gred: "Gred" },
    { name: "Sains Pertanian", gred: "Gred" },
    { name: "Reka Cipta", gred: "Gred" },
    { name: "Teknologi Maklumat", gred: "Gred" },
    { name: "Kesusasteraan Melayu", gred: "Gred" },
    { name: "Literature in English", gred: "Gred" },
    { name: "Kesusasteraan Cina", gred: "Gred" },
    { name: "Kesusasteraan Tamil", gred: "Gred" },
    { name: "Pendidikan Seni Visual", gred: "Gred" },
    { name: "Ekonomi Rumah Tangga", gred: "Gred" },
    { name: "Pendidikan Muzik", gred: "Gred" },
    { name: "Sains Tambahan", gred: "Gred" },
    { name: "Sains", gred: "Gred" },
    { name: "Ekonomi Asas", gred: "Gred" },
    { name: "Prinsip Perakaunan", gred: "Gred" },
    { name: "Perdagangan", gred: "Gred" },
    { name: "Geografi", gred: "Gred" },
    { name: "Pendidikan Al-Quran dan As-Sunnah", gred: "Gred" },
    { name: "Pendidikan Syariah Islamiah", gred: "Gred" },
    { name: "Tasawwur Islam", gred: "Gred" },
    { name: "Bahasa Arab Tinggi", gred: "Gred" },
    { name: "Matematik Tambahan", gred: "Gred" },
    { name: "Physics", gred: "Gred" },
    { name: "Chemistry", gred: "Gred" },
    { name: "Biology", gred: "Gred" },
    { name: "English for Science and Technology", gred: "Gred" },
    { name: "Pengajian Kejuruteraan Awam", gred: "Gred" },
    { name: "Pengajian Kejuruteraan Elektrik", gred: "Gred" },
    { name: "Pengajian Keusahawanan", gred: "Gred" },
    { name: "Lukisan Kejuruteraan", gred: "Gred" },
];

export default SPMSubject;
